// WARNING: other projects also depends on this file for quotes
// T24

const Quotes = [
    ["", "C'est juste un arrêt, pas le terminus."],
    ["", "Event a broken clock is right twice a day"],
    ["", "Even if I am a free wind, I'll cherish those who love me"],
    ["", "Everybody is an astronaut because the Earth, after all, is in space"],
    ["", "The world is better with you in it"],
    ["", "Please have a good day. If your day is not good, maybe tomorrow will be a good day"],
    ["", "Rules are made to be broken and you are made to be happy"],
    ["", "Study while others are sleeping; work while others are loafing; prepare while others are playing; and dream while others are wishing"],
    ["", "When there is an elephant in the room, introduce him"],
    ["kz and 八王子P and 栗山夕璃, トリコロール (Tricolor) (Tackmyn Y. translation)", "Whatever future lies ahead, you will be all right.\nYou'll illuminate it with the light you're yet to know."],
    ["KZ-Livetune, ジュビリ", "We searched so long for perfect sound, in midst of crying, we're always laughing, and that's what's pushing us along."],
    ["KZlivetune, Far Away (bambooXZX's translation)", "Maybe I'll come to love the unknown tomorrow"],
    ["Nanatsukaze, Harumeku", "I'd like to live like a cat someday\nHuman desires are foolish"],
    ["*Luna, Check This Out", "No matter what anyone said, I want you to notice it\nCheck this out!"],
    ["*Luna, 夏が僕らを呼ぶのなら (If Summer is calling us) ", "If there aren't enough promises, let's make them again and again"],
    ["*Luna, 夏が僕らを呼ぶのなら (If Summer is calling us) ", "We can surely become stronger, we can look up, and we can walk again"],
    ["*Luna, 10年後の私になら / Only to me in 10 years (Kohana Lam's translation)", "It is not your fault that you cannot be strong."],
    ["*Luna, 10年後の私になら / Only to me in 10 years (Kohana Lam's translation)", "You are still sneaky, aren't you?\nYou can't wait to escape"],
    ["*Luna, 10年後の私になら / Only to me in 10 years (Kohana Lam's translation)", "You may not be able to run with these legs, but you are the one who chose trying to walk somehow"],
    ["*Luna, あの夏のいつかは (Someday in that Summer)", "Failure is not scary at all, what's scary is to not leave anything behind"],
    ["Mili, YUBIKIRI-GENMAN", "It's okay if you take a break\nFor I will never stop"],
    ["OMORI, BASIL", "The photos in our album... They're not just photo. They're real memories."],
    ["OMORI, HERO", "Life gets better. You just have to stay positive."],
    ["OMORI, MEWO", "Meow? (Not much to do around here, is there?)"],
    ["OMORI, MEWO", "Meow? (Waiting for something to happen?)"],
    ["Orangestar, Daydream Skytrain (Translyrics by rachie)", "But if we just focus on things that annoy us, we might miss the stars"],
    ["Orangestar, Daydream Skytrain (Translyrics by rachie)", "Hey, don't just wait — make it happen instead"],
    ["Orangestar, Daydream Skytrain (Translyrics by rachie)", "If we're gonna waste the summer, might as well we make them remember just what we can be"],
    ["PIKASONIC, First Magnitude Star", "I want to sing this song to you, who can't shine in a simple world"],
    ["Qeiru, フィクション (Fiction)", "Let's rest a little longer, until the sadness melts away"],
    ["Qeiru, フィクション (Fiction)", "...even if that's the case, my imagination, my adventure, is not a lie"],
    ["Qeiru, 世界線第二ターミナル (World Line Terminal 2)", "Hating the hopeless present, I throw it away, saying I don't know anymore"],
    ["Yoshida, 夏空のSELFISH (Selfish in the summer sky)", "A small happiness is fine<br>don't need anything else"],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
    // ["", ""],
];